import Download from "@mui/icons-material/Download";

const engTranslate  = 
    
    {
        //Header Portion
        header_login:'Login',
        header_register:'Register',
        header_logout:'Logout',

        //Login Portion
        login_header:"Account Login",
        email_title:'Email',
        enter_email: "Please enter email",
        email_required: "Email is required",
        email_error: "Email address is invalid",
        enter_password: "Please enter your password",
        password_required: "Password is required",
        login_password:'Password is required',
        password_error: 'Passwords must be at least 8 chars with at least 1 uppercase, 1 lowercase, 1 number and 1 special character.',
        password_title:'Password',
        forgot_title:'Have you forgotten your password?',
        login_button:'Login',
        register_title:'Do not have an account?',
        register_button:'Register',
        login_success_msg:'Logged in successfully',
        login_error_msg:'Credetionals does not match',

        //Register
        register_title:'Account Registration',
        exist_email:'Already Email Exist',
        serial_id_title:'Serial Code ID',
        enter_serial_id:'Please enter your serial code id',
        serial_id_required:'Serial code Id is required',
        serial_match:'Serial code Id is verify',
        serial_not_match:'Serial code Id is wrong',
        refrence_person_title:'Reference person(*)',
        company_title:'Company Name',
        enter_company: "Please enter company name",
        company_required: "Company name is required",
        lname_title:'Last Name',
        enter_lname: "Please enter last name",
        lname_required: "Last name is required",
        fname_title:'First Name',
        enter_fname: "Please enter first name",
        fname_required: "First name is required",
        cell_title:'Cell',
        enter_cell: "Please enter your cell number",
        cell_required: "Cell number is required",
        register_button:'Register Account',
        register_success_msg:'Successfully Register',
        register_error_msg:'Something Went Wrong',
        reg_email_exist:'Email ID is already exist',
        serial_code_invalid:'Invalid device serial id provided',
        serial_code_expire:'This device serial Id is already used',

        //Forgot Password
        forget_title:'Did you forget your password?',
        forget_title_2:'To start the password reset procedure enter your email address',
        forget_title_3:'We sent an email to',
        forget_title_4:'massimocalieri@hotmail.it',
        forget_title_5:'with instructions to reset the password',
        forgot_button:'Reset',
        forgot_email_err_msg:'User not found with this email ID',
        forgot_email_success_msg:'Check your email for OTP',

        //Reset Password
        reset_title:'Reset Password',
        security_code_title:'Security Code',
        enter_security_code:'Please enter security code',
        security_code_required:'security code is required',
        conf_password_required: "Password is required",
        conf_password_error: 'Passwords must be at least 8 chars with at least 1 uppercase, 1 lowercase, 1 number and 1 special character.',
        conf_password_title:'Confirm Password',
        enter_confirm_password:'Please enter your confirm password',
        forgot_button:'Submit',
        password_not_match:'Password Does Not Match',
        forget_success_msg:'Password Update Successfully',
        forget_error_msg:'Something Went Wrong',

        // Project Page
        create_project_button:'Create Project',
        modal_cancel:'Cancel',
        modal_delete:'Delete',
        del_project_title:'Are You Sure you want to delete this Project?',
        tbl_project_name:'Project Name',
        tbl_status:'Status',
        tbl_edit:'Edit',
        tbl_download:'Download',
        tbl_project_delete:'Delete',
        no_records:'No Records Found!',
        project_del:'Project Deleted Successfully',
        project_del_err:'Unable to delete the project',

        //Create Project Page
        project_title_header:'Create Project',
        project_title:'Project Name',
        enter_project:'Please enter project name',
        project_required:'Project Name is required',
        option_heading:'Select Template',
        template_name_1:'Lamps(On)+Display',
        template_name_2:'Lamps(Off)+Display',
        template_name_3:'Lamps(On) Without Display',
        template_name_4:'Without Lamps-Only Display',
        start_time_title:'Start Time',
        start_time_required:'Start time is required',
        end_time_title:'End Time',
        end_time_required:'End time is required',
        item_speed_title:'Item Speeds',
        item_speed_fast:'Fast',
        item_speed_normal:'Normal',
        item_speed_slow:'Slow',
        no_more_items:'Sorry, only you can create 4 Items',
        item_speed_required:'Item speed is required',
        upload_images_required:'Minimum 2 Images Upload',
        no_more_images:'Sorry, only you can upload 4 images of Items',

        upload_logo_title:'Upload Logo',
        upload_action_image_title:'Upload call to action image',
        item_name_title:'Item Name',
        enter_item_name:'Please enter item name',
        item_name_required:'Item name is required',

        lamp_number_title:'Lamp Number',
        enter_lamp_number:'Please enter lamp number',
        lamp_number_required:'Lamp number  is required',
        unique_lamp_title:'Please enter unique Lamp Number',
        lamp_no_more_items:'No More Items',
        upload_images_title:'Upload Images',
        save_photo_title:'Save Photo',
        delete_photo_title:'Delete Photo',
        save_template_title:'Save Template',
        new_temp_butt:'Add New Template',
        submit_butt:'Submit Project',
        temp_add_msg:'Template Add Succesfully',
        add_photo_msg:'Photos Add Successfully',
        submit_err_required:'Its seem that there is an error in your form, Please check again',
        submit_err_msg:'Please make sure your templates is completing the min 24 hours',
        submit_success_msg:'Your Booking Complete 24 hours. Please click on generate Button to confirm',
        upload_video_title:'Upload Video',
        del_video_title:'Delete Video',
        required_video:'Upload video is required',
        video_type_err:'Please Upload only Video and type is mp4',

        //Submmission Project Details
        final_file_generation:'Final File Generation',
        file_generation:'File Generation',
        temp_name:'Template Name',
        event_scheduled:'Event Time Scheduled',
        from:'From',
        to:'To',
        generate:'GENERATE',
        preview_video:'Preview Video',
        project_success_msg:'Project Create Successfully',
        project_err_msg:'Something Went Wrong',
        project_update_msg:'Project Update Successfully',


        //Update Page
        update_project_title:'title',
        update_butt:'Update Project',

        //Email Notify page
        email_notify_title_1:'Check Your Email',
        email_notify_title_2:'Confirm the creation of your account via the email we sent you to',
        email_notify_title_3:`If you can't find the email, check it in spam`,
        email_notify_title_4:'You have 48 hours',
        //Important Notes
        heading_notes:'Importance of',
        sub_heading:' Vetrine',
        first_line:'Reply to an ad with a click or call the seller directly',
        second_line:'You only consult ads that have been checked prior to publication',
        third_line:'Save the ads or searches that interest you and review them whenever you want',
        fourth_line:'You can see the reviews and leave your feedback',
       
        internal_server_error:'Internal Server Error',
        login_error:'Please Login First',
        token_error: 'Auth Token Verification Failed'
    }

export default engTranslate; 
