const itTranslate  = 
    {
        //Header Portion
        header_login:'Accedere',
        header_register:'Registrati',
        header_logout:'Disconnettersi',
        
        //Login Portion
        login_header:"Account Accedere",
        email_title:'E-mail',
        enter_email: "Inserisci l'e-mail",
        email_required: "L'e-mail è obbligatoria",
        email_error: "l'indirizzo email non è valido",
        enter_password: "per favore inserisci LA TUA password",
        password_required: "E 'richiesta la password",
        login_password:"E 'richiesta la password",
        password_error: 'Le password devono essere di almeno 8 caratteri con almeno 1 maiuscolo, 1 minuscolo, 1 numero e 1 carattere speciale.',
        password_title:"Parola d'ordine",
        forgot_title:'Hai dimenticato la tua password?',
        login_button:'Accedere',
        register_title:'Non hai un account?',
        register_button:'Registrati',
        login_success_msg:'Accesso effettuato con successo',
        login_error_msg:'Le credenziali non corrispondono',
        
         //Register
         register_title:"Registrazione dell'account",
         exist_email:"L'e-mail esiste già",
         serial_id_title:'ID codice seriale',
         enter_serial_id:"Si prega di inserire l'ID del codice seriale",
         serial_id_required:`L'ID del codice seriale è obbligatorio`,
         serial_match:`L'ID del codice seriale è verificato`,
         serial_not_match: `L'ID del codice seriale è errato`,
         refrence_person_title:'Referente(*)',
         company_title:'Nome della ditta',
         enter_company: `Inserisci il nome dell'azienda`,
         company_required: `Il nome dell'azienda è obbligatorio`,
         lname_title:'Cognome',
         enter_lname: "Inserisci il cognome",
         lname_required: `Il cognome è obbligatorio`,
         fname_title:'Nome di battesimo',
         enter_fname: "Inserisci il nome",
         fname_required: `Il nome è obbligatorio`,
         cell_title:'Cellula',
         enter_cell: "Inserisci il tuo numero di cellulare",
         cell_required: `Il numero di cellulare è obbligatorio`,
         register_button:'Registra conto',
         register_success_msg:'Registrati con successo',
         register_error_msg:`Qualcosa è andato storto`,
         reg_email_exist: "L'ID e-mail esiste già",
         serial_code_invalid:'ID seriale del dispositivo fornito non valido',
         serial_code_expire:'Questo ID seriale del dispositivo è già utilizzato',
 
         //Forgot Password
         forget_title:'Hai dimenticato la tua password?',
         forget_title_2:'Per avviare la procedura di reimpostazione della password inserisci il tuo indirizzo email',
         forget_title_3:'Abbiamo inviato una mail a',
         forget_title_4:'massimocalieri@hotmail.it',
         forget_title_5:'con le istruzioni per reimpostare la password',
         forgot_button:'Ripristina',
         forgot_email_err_msg:'Utente non trovato con questo ID email',
         forgot_email_success_msg:'Controlla la tua e-mail per OTP',
 
         //Reset Password
         reset_title:'Resetta la password',
         security_code_title:'Codice di sicurezza',
         enter_security_code:'Inserisci il codice di sicurezza',
         security_code_required:`è richiesto il codice di sicurezza`,
         conf_password_required: `E 'richiesta la password`,
         conf_password_error: 'Le password devono essere di almeno 8 caratteri con almeno 1 maiuscolo, 1 minuscolo, 1 numero e 1 carattere speciale.',
         conf_password_title:'Conferma password',
         enter_confirm_password:'Inserisci la tua password di conferma',
         forgot_button:'Invia',
         password_not_match:'La password non corrisponde',
         forget_success_msg:'Aggiornamento password riuscito',
         forget_error_msg:`Qualcosa è andato storto`,
 
         // Project Page
         create_project_button:'Crea progetto',
         modal_cancel:'Annulla',
         modal_delete:'Elimina',
         del_project_title:'Sei sicuro di voler eliminare questo progetto?',
         tbl_project_name:'Nome del progetto',
         tbl_status:'Stato',
         tbl_edit:'Modificare',
         tbl_download:'Scarica',
         tbl_project_delete:'Elimina',
         no_records:'Nessun record trovato!',
         project_del:'Progetto eliminato con successo',
         project_del_err:'Impossibile eliminare il progetto',

 
         //Create Project Page
         project_title_header:'Crea progetto',
         project_title:'Nome del progetto',
         enter_project:'Inserisci il nome del progetto',
         project_required:`Il nome del progetto è obbligatorio`,
         option_heading:'Seleziona Modello',
         template_name_1:'Lampade(Acceso)+Display',
         template_name_2:'Lampade(Off)+Display',
         template_name_3:'Lampade (accese) senza display',
         template_name_4:'Senza display solo lampade',
         start_time_title:'Ora di inizio',
         start_time_required:`L'ora di inizio è obbligatoria`,
         end_time_title:'Tempo scaduto',
         end_time_required:`L'ora di fine è obbligatoria`,
         item_speed_title:'Voce Velocità',
         item_speed_fast:'Veloce',
         item_speed_normal:'Normale',
         item_speed_slow:'Lento',
         no_more_items:'Siamo spiacenti, solo tu puoi creare 4 elementi',
         item_speed_required:`La velocità dell'articolo è obbligatoria`,
         upload_images_required:'Caricamento minimo di 2 immagini',
         no_more_images:'Siamo spiacenti, solo tu puoi caricare 4 immagini di Articoli',
 
         upload_logo_title:'Carica logo',
         upload_action_image_title:`Carica l'immagine di invito all'azione`,
         item_name_title:`Nome dell'oggetto`,
         enter_item_name:`Inserisci il nome dell'elemento`,
         item_name_required:`Il nome dell'elemento è obbligatorio`,
 
         lamp_number_title:'Numero lampada',
         enter_lamp_number:'Inserisci il numero della lampada',
         lamp_number_required:`Il numero della lampada è obbligatorio`,
         unique_lamp_title:'Si prega di inserire un numero di lampada univoco',
         lamp_no_more_items:'Niente più articoli',
         upload_images_title:'Carica immagini',
         save_photo_title:'Salva foto',
         delete_photo_title:'Elimina foto',
         save_template_title:'Salva modello',
         new_temp_butt:'Aggiungi nuovo modello',
         submit_butt:'Invia progetto',
         temp_add_msg:'Modello aggiunto con successo',
         add_photo_msg:'Foto aggiunte con successo',
         submit_err_required:'Sembra che ci sia un errore nel tuo modulo, controlla di nuovo',
         submit_err_msg:'Assicurati che i tuoi modelli stiano completando le 24 ore minime',
         submit_success_msg:'La tua prenotazione completa 24 ore. Fare clic sul pulsante Genera per confermare',
         upload_video_title:'Carica video',
         del_video_title:'Elimina video',
         required_video:'È necessario caricare il video',
         video_type_err:'Si prega di caricare solo video e il tipo è mp4',
 
         //Submmission Project Details
         final_file_generation:'Generazione file finale',
         file_generation:'Generazione file',
         temp_name:'Nome modello',
         event_scheduled:`Orario dell'evento programmato`,
         from:'Da',
         to:'Per',
         generate:'CREARE',
         preview_video:'Video di anteprima',
         project_success_msg:'Progetto creato con successo',
         project_err_msg:'Qualcosa è andato storto',
         project_update_msg:'Aggiornamento del progetto riuscito',

         //Update Page
         update_project_title:'Aggiorna progetto',
         update_butt:'Aggiorna progetto',

        //Email Notify page
        email_notify_title_1:'Controlla la tua e-mail',
        email_notify_title_2:`Conferma la creazione del tuo account tramite l'e-mail che ti abbiamo inviato`,
        email_notify_title_3:`Se non riesci a trovare l'e-mail, controllala nello spam`,
        email_notify_title_4:'Hai 48 ore',

        //Important Notes
        heading_notes:'Importanza di',
        sub_heading:' Vetrina',
        first_line:'Rispondi a un annuncio con un clic o chiama direttamente il venditore',
        second_line:'Consulta solo gli annunci che sono stati controllati prima della pubblicazione',
        third_line:'Salva gli annunci o le ricerche che ti interessano e rivedili quando vuoi',
        fourth_line:'Puoi vedere le recensioni e lasciare il tuo feedback',
        internal_server_error:'Errore interno del server',
        login_error:'Per favore fai prima il log in',
        token_error: 'Verifica del token di autenticazione non riuscita'

    }

export default itTranslate; 